//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raumplanung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Teacher { get; set; }
    
        public virtual Teacher Teacher1 { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
